package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/vyrwu/atelier/internal/initgen"
)

// InitCommand emits the tmux.conf block for plugin-mode embedding.
// Calls into initgen.Render — the same primitive the bundled
// launcher (`atelier` no subcommand) uses. Single source of truth
// for what a "complete atelier config" looks like.
//
// Two flag-controlled modes:
//
//	atelier init           - engine + theme (default).
//	                         For users who want the curated visual
//	                         identity layered into their existing tmux.
//
//	atelier init --bare    - engine only. No theme.
//	                         For users who own the visual layer
//	                         themselves and just want atelier's
//	                         behavioral primitives.
//
// Both modes emit the engine wiring identically: popup-shim, tool
// bindings, core bindings, hooks, statusline-injection, restore.
// The only difference is whether ThemeBlock() is included.
//
// Neither plugin-mode call emits the ATELIER_TMUX_SOCKET env line —
// plugin-mode is sourced INTO the user's host tmux, where TMUX env
// is already set and routes run-shell children correctly. The
// bundled launcher's runCmd path passes a Socket value to Render;
// init mode passes empty.
func InitCommand() *cobra.Command {
	var bare bool
	c := &cobra.Command{
		Use:   "init",
		Short: "Print tmux.conf snippet wiring atelier",
		Long: `Print a tmux config block that wires atelier into tmux.

Default (engine + theme): the full bundled config. Sourced by the
` + "`atelier`" + ` launch command, or by users who want the bundled
experience layered into an existing tmux config:

    run-shell 'atelier init | tmux source-file -'

--bare (engine only): just bindings, hooks, statusline segment
injection — no theme, no statusline format changes. For users who
have their own tmux theme and statusline and only want atelier's
behavior:

    run-shell 'atelier init --bare | tmux source-file -'

Bindings come from each discovered tool's manifest (via plugin
discovery). The core has no built-in knowledge of any specific tool.`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			out := cmd.OutOrStdout()
			mode := "engine + theme"
			if bare {
				mode = "engine only (bare)"
			}
			header := fmt.Sprintf("# Generated by atelier init (%s) -- do not edit by hand\n"+
				"# Regenerate: run-shell 'atelier init | tmux source-file -'", mode)
			res, err := initgen.Render(out, initgen.RenderOptions{
				Socket:       "", // plugin mode: TMUX env routes
				IncludeTheme: !bare,
				Header:       header,
			})
			if err != nil {
				return err
			}
			if len(res.Skipped) > 0 {
				fmt.Fprintln(out)
				fmt.Fprintln(out, "# Skipped tools (manifest errors):")
				for path, err := range res.Skipped {
					fmt.Fprintf(out, "#   %s: %v\n", path, err)
				}
			}
			return nil
		},
	}
	c.Flags().BoolVar(&bare, "bare", false,
		"emit engine wiring only; skip the bundled theme + statusline format")
	return c
}
