package core

import "crypto/rand"

// FriendlyName generates an instant, recognizable "adjective-noun" reference for
// a workspace (its dir + session name), e.g. "brave-otter". It carries no
// meaning about the task — the workspace Title (generated by Claude) does that —
// but it is stable, pronounceable, and easy to refer to. Uniqueness is enforced
// by AddUniqueWorkspace, not here.
func FriendlyName() string {
	return friendlyAdjectives[randN(len(friendlyAdjectives))] + "-" +
		friendlyNouns[randN(len(friendlyNouns))]
}

// randN returns a uniformly-ish random index in [0,n) from crypto/rand. Bias at
// this scale is irrelevant for names.
func randN(n int) int {
	var b [1]byte
	_, _ = rand.Read(b[:])
	return int(b[0]) % n
}

var friendlyAdjectives = []string{
	"amber", "bold", "brave", "bright", "calm", "clever", "cosmic", "crisp",
	"dawn", "deep", "eager", "fair", "fleet", "gentle", "glad", "grand",
	"keen", "lucid", "lunar", "mellow", "merry", "mild", "noble", "quiet",
	"rapid", "ruby", "sage", "sharp", "sleek", "snug", "solar", "spry",
	"still", "swift", "teal", "tidy", "vivid", "warm", "wise", "zesty",
}

var friendlyNouns = []string{
	"otter", "harbor", "meadow", "falcon", "cedar", "comet", "delta", "ember",
	"fjord", "grove", "heron", "ibex", "jetty", "kelp", "lark", "lynx",
	"maple", "nimbus", "orchid", "pine", "quartz", "reef", "robin", "spruce",
	"summit", "thistle", "tundra", "vale", "willow", "wren", "badger", "basin",
	"brook", "cove", "dune", "glen", "koala", "ridge", "sparrow", "birch",
}
